"""Convert a local ISODISTORT Method-2 session into GD notebook inputs.

Writes the files ``LD1_C1_gradient_descent_tianren.ipynb`` already reads:

* ``{prefix}_mario_mode_names.txt``
* ``{prefix}_norm_factors.txt``
* ``{prefix}_max_bound_vectors.txt``
* ``{prefix}_displacive_modes.txt``
* ``{prefix}_alris_functions.py``  (``atom_position_list``, structure factors)

Default output is ``generated/{irrep}_{opd}/`` in this folder.  Original
OneDrive refinement files under ``D:\\OneDrive\\...`` are never overwritten.
The tianren notebook is never modified.

Run with the CRIS ``.venv`` (needs WSL iso/smodes), for example:

    C:\\Users\\devou\\OneDrive\\Desktop\\CRIS\\.venv\\Scripts\\python.exe
    isodistort_to_gd.py --irrep LD1 --opd C1 --k LD --k-params 1/6
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import numpy as np

GD_ROOT = Path(__file__).resolve().parent
DEFAULT_CRIS = Path(r"C:\Users\devou\OneDrive\Desktop\CRIS")
DEFAULT_CIF = DEFAULT_CRIS / "experiment_data" / "EuAl4 Parent.cif"


# ---------------------------------------------------------------------------
# File writers (no ISODISTORT / TensorFlow)
# ---------------------------------------------------------------------------

def _no_space(text: str) -> str:
    return re.sub(r"\s+", "", str(text).strip()) or "mode"


def write_mario_mode_names(path: Path, names: Sequence[str]) -> None:
    path.write_text("".join(f"{_no_space(n)}\n" for n in names), encoding="utf-8")


def write_comma_row(path: Path, values: Sequence[float]) -> None:
    path.write_text(
        ",".join(f"{float(v):.8g}" for v in values) + "\n",
        encoding="utf-8",
    )


def write_displacive_modes(path: Path, names: Sequence[str]) -> None:
    lines = [f"{i} {_no_space(name)}" for i, name in enumerate(names, start=1)]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _py_float_array(name: str, arr: np.ndarray, indent: str = "") -> str:
    arr = np.asarray(arr, dtype=np.float32)
    flat = ", ".join(f"{float(x):.8g}" for x in arr.ravel())
    return (
        f"{indent}{name} = np.array([{flat}], dtype=np.float32)"
        f".reshape{tuple(int(n) for n in arr.shape)}\n"
    )


def render_alris_functions(
    *,
    names: Sequence[str],
    species: Sequence[str],
    base_frac: np.ndarray,
    mode_frac: np.ndarray,
    lattice: np.ndarray,
    hkl_transform: np.ndarray,
    parent_symbol: str,
    irrep: str,
    opd: str,
) -> str:
    """Generate a self-contained TensorFlow module the notebook can import."""
    names = [_no_space(n) for n in names]
    species = [str(s) for s in species]
    base_frac = np.asarray(base_frac, dtype=np.float32)
    mode_frac = np.asarray(mode_frac, dtype=np.float32)
    lattice = np.asarray(lattice, dtype=np.float32)
    hkl_transform = np.asarray(hkl_transform, dtype=np.float32)
    n_modes, n_atoms, _ = mode_frac.shape
    if base_frac.shape != (n_atoms, 3):
        raise ValueError(
            f"base_frac {base_frac.shape} does not match mode_frac {mode_frac.shape}"
        )
    if len(names) != n_modes:
        raise ValueError(f"{len(names)} names vs {n_modes} mode vectors")
    if len(species) != n_atoms:
        raise ValueError(f"{len(species)} species vs {n_atoms} atoms")
    inv_lat = np.linalg.inv(lattice)
    reciprocal = 2.0 * math.pi * inv_lat.T
    header = f'''"""TensorFlow structure-factor helpers generated from ISODISTORT.

Parent: {parent_symbol}   IR: {irrep}   OPD: {opd}
{n_modes} displacive modes on a {n_atoms}-atom child cell.

``transform_list_hkl_p63_p65`` keeps the historical name imported by
``LD1_C1_gradient_descent_tianren.ipynb``.  It maps parent HKL onto the
child supercell (``hkl_child = hkl_parent @ HKL_TRANSFORM``).

Do not edit this file by hand; regenerate with ``isodistort_to_gd.py``.
"""
from __future__ import annotations

import numpy as np
import tensorflow as tf

N_MODES = {n_modes}
N_ATOMS = {n_atoms}
MODE_NAMES = {names!r}
SPECIES = {species!r}

'''
    body = (
        _py_float_array("BASE_FRAC", base_frac)
        + _py_float_array("MODE_FRAC", mode_frac)
        + _py_float_array("LATTICE", lattice)
        + _py_float_array("HKL_TRANSFORM", hkl_transform)
        + _py_float_array("RECIPROCAL", reciprocal.astype(np.float32))
    )
    footer = r'''
_BASE_TF = tf.constant(BASE_FRAC)
_MODE_TF = tf.constant(MODE_FRAC)
_HKL_T_TF = tf.constant(HKL_TRANSFORM)
_RECIP_TF = tf.constant(RECIPROCAL)

# Cromer–Mann coefficients (ITC): f(s) = Σ a_i exp(-b_i s²) + c, s = |Q|/(4π)
_FF_TABLE = {
    "H":  (0.489918, 0.262003, 0.196767, 0.049879, 20.6593, 7.74039, 49.5519, 2.20159, 0.001305),
    "C":  (2.31000, 1.02000, 1.58860, 0.865000, 20.8439, 10.2075, 0.568700, 51.6512, 0.215600),
    "N":  (12.2126, 3.13220, 2.01250, 1.16630, 0.005700, 9.89330, 28.9975, 0.582600, -11.529),
    "O":  (3.04850, 2.28680, 1.54630, 0.867000, 13.2771, 5.70110, 0.323900, 32.9089, 0.250800),
    "AL": (6.42020, 1.90020, 1.59360, 1.96460, 3.03870, 0.742600, 31.54720, 85.0886, 1.11510),
    "SI": (6.29150, 3.03530, 1.98910, 1.54100, 2.43860, 32.3337, 0.678500, 81.6937, 1.14070),
    "CA": (8.62660, 7.38730, 1.58990, 1.02110, 10.4421, 0.659900, 85.7484, 178.437, 1.37510),
    "TI": (9.75950, 7.35580, 1.69910, 1.90210, 7.85080, 0.500000, 35.6338, 116.105, 1.28070),
    "FE": (11.7695, 7.35730, 3.52220, 2.30450, 4.76110, 0.307200, 15.3535, 76.8805, 1.03690),
    "NI": (12.8376, 7.29200, 3.24470, 2.40380, 3.87850, 0.256500, 12.1763, 66.3421, 1.06960),
    "SR": (17.5663, 9.81840, 5.42200, 2.66940, 1.55640, 14.0988, 0.166400, 132.376, 2.50640),
    "ND": (22.6845, 19.6847, 12.7740, 4.91295, 2.66248, 0.210628, 15.8850, 98.5624, 1.69714),
    "EU": (24.627839, 19.248600, 13.768376, 4.346566, 2.18020, 0.202172, 26.890785, 85.264068, 2.936082),
}
_Z_FALLBACK = {
    "H": 1.0, "C": 6.0, "N": 7.0, "O": 8.0, "AL": 13.0, "SI": 14.0,
    "CA": 20.0, "TI": 22.0, "FE": 26.0, "NI": 28.0, "SR": 38.0,
    "ND": 60.0, "EU": 63.0,
}


def _element_key(label: str) -> str:
    return "".join(ch for ch in str(label) if ch.isalpha()).upper() or "AL"


_FF_A = np.zeros((N_ATOMS, 4), dtype=np.float32)
_FF_B = np.zeros((N_ATOMS, 4), dtype=np.float32)
_FF_C = np.zeros((N_ATOMS,), dtype=np.float32)
for _i, _sp in enumerate(SPECIES):
    _key = _element_key(_sp)
    if _key in _FF_TABLE:
        _a1, _a2, _a3, _a4, _b1, _b2, _b3, _b4, _c = _FF_TABLE[_key]
        _FF_A[_i] = (_a1, _a2, _a3, _a4)
        _FF_B[_i] = (_b1, _b2, _b3, _b4)
        _FF_C[_i] = _c
    else:
        _FF_C[_i] = _Z_FALLBACK.get(_key, 1.0)
_FF_A_TF = tf.constant(_FF_A)
_FF_B_TF = tf.constant(_FF_B)
_FF_C_TF = tf.constant(_FF_C)


def transform_list_hkl_p63_p65(hkl_list):
    """Map parent HKL onto the child supercell (historical function name)."""
    hkl = tf.cast(tf.convert_to_tensor(hkl_list), tf.float32)
    if hkl.shape.rank == 1:
        hkl = tf.reshape(hkl, (1, 3))
    return tf.matmul(hkl, _HKL_T_TF)


def atom_position_list(*amplitudes):
    """Return child-cell fractional coordinates, differentiable in ``amplitudes``."""
    if len(amplitudes) != N_MODES:
        raise ValueError(f"expected {N_MODES} amplitudes, got {len(amplitudes)}")
    amps = tf.stack([tf.cast(a, tf.float32) for a in amplitudes])
    amps = tf.reshape(amps, (N_MODES,))
    delta = tf.tensordot(amps, _MODE_TF, axes=[[0], [0]])
    return _BASE_TF + delta


def _form_factors(hkl):
    qvec = tf.matmul(tf.cast(hkl, tf.float32), _RECIP_TF)
    s2 = tf.reduce_sum(qvec * qvec, axis=1, keepdims=True) / tf.constant(
        (16.0 * np.pi ** 2), dtype=tf.float32
    )
    expo = tf.exp(-tf.expand_dims(_FF_B_TF, 0) * tf.expand_dims(s2, 2))
    ff = tf.reduce_sum(tf.expand_dims(_FF_A_TF, 0) * expo, axis=2)
    return ff + tf.expand_dims(_FF_C_TF, 0)


def get_structure_factors(hkl_list, struct):
    """F(hkl) = Σ_j f_j(|Q|) exp(2πi h·r_j) on the child cell."""
    hkl = tf.cast(tf.convert_to_tensor(hkl_list), tf.float32)
    xyz = tf.cast(tf.convert_to_tensor(struct), tf.float32)
    phase = (2.0 * np.pi) * tf.matmul(hkl, tf.transpose(xyz))
    ff = _form_factors(hkl)
    real = tf.reduce_sum(ff * tf.cos(phase), axis=1)
    imag = tf.reduce_sum(ff * tf.sin(phase), axis=1)
    return tf.complex(real, imag)


def get_structure_factors_CO(hkl_list, struct, base_struct=None):
    """Charge-order variant; occupancy modulation is not generated here."""
    del base_struct
    return get_structure_factors(hkl_list, struct)
'''
    return header + body + footer


@dataclass
class GdBundle:
    names: list[str]
    norm_factors: np.ndarray
    max_bounds: np.ndarray
    species: list[str]
    base_frac: np.ndarray
    mode_frac: np.ndarray
    lattice: np.ndarray
    hkl_transform: np.ndarray
    parent_symbol: str
    irrep: str
    opd: str
    metadata: dict[str, Any]


def write_gd_bundle(
    out_dir: Path,
    prefix: str,
    bundle: GdBundle,
    *,
    install_alris: Path | None = None,
) -> dict[str, Path]:
    """Write notebook inputs.  Returns the paths that were created."""
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = out_dir / prefix
    written = {
        "mario_mode_names": Path(f"{stem}_mario_mode_names.txt"),
        "norm_factors": Path(f"{stem}_norm_factors.txt"),
        "max_bound_vectors": Path(f"{stem}_max_bound_vectors.txt"),
        "displacive_modes": Path(f"{stem}_displacive_modes.txt"),
        "alris_functions": out_dir / f"{prefix}_alris_functions.py",
        "metadata": out_dir / "metadata.json",
    }
    write_mario_mode_names(written["mario_mode_names"], bundle.names)
    write_comma_row(written["norm_factors"], bundle.norm_factors)
    write_comma_row(written["max_bound_vectors"], bundle.max_bounds)
    write_displacive_modes(written["displacive_modes"], bundle.names)
    alris = render_alris_functions(
        names=bundle.names,
        species=bundle.species,
        base_frac=bundle.base_frac,
        mode_frac=bundle.mode_frac,
        lattice=bundle.lattice,
        hkl_transform=bundle.hkl_transform,
        parent_symbol=bundle.parent_symbol,
        irrep=bundle.irrep,
        opd=bundle.opd,
    )
    written["alris_functions"].write_text(alris, encoding="utf-8")
    written["metadata"].write_text(
        json.dumps(bundle.metadata, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    if install_alris is not None:
        install_alris.parent.mkdir(parents=True, exist_ok=True)
        install_alris.write_text(alris, encoding="utf-8")
        written["installed_alris"] = install_alris
    return written


def check_bundle(bundle: GdBundle) -> list[str]:
    """Cheap numpy sanity checks (no TensorFlow)."""
    errors: list[str] = []
    n_modes = int(bundle.mode_frac.shape[0])
    n_atoms = int(bundle.mode_frac.shape[1])
    if n_modes != len(bundle.names):
        errors.append(f"mode count {n_modes} != names {len(bundle.names)}")
    if bundle.base_frac.shape != (n_atoms, 3):
        errors.append(f"base_frac shape {bundle.base_frac.shape}")
    if len(bundle.species) != n_atoms:
        errors.append("species length mismatch")
    if int(bundle.norm_factors.shape[0]) != n_modes:
        errors.append("norm_factors length mismatch")
    if int(bundle.max_bounds.shape[0]) != n_modes:
        errors.append("max_bounds length mismatch")
    if n_modes == 0:
        errors.append("no displacive modes")
        return errors
    recovered = bundle.base_frac + np.tensordot(
        np.zeros(n_modes, dtype=np.float32), bundle.mode_frac, axes=(0, 0)
    )
    if float(np.max(np.abs(recovered - bundle.base_frac))) > 1e-6:
        errors.append("zero amplitudes do not recover the base cell")
    moved = float(np.max(np.abs(bundle.mode_frac[0])))
    if moved < 1e-12:
        errors.append("first mode vector is identically zero")
    return errors


# ---------------------------------------------------------------------------
# ISODISTORT session → GdBundle
# ---------------------------------------------------------------------------

def _ensure_isocore(cris_root: Path) -> None:
    iso_dir = cris_root / "ISODISTORT"
    if not iso_dir.is_dir():
        raise FileNotFoundError(f"ISODISTORT not found at {iso_dir}")
    text = str(iso_dir)
    if text not in sys.path:
        sys.path.insert(0, text)


def _hkl_transform_from_basis(basis: Sequence[Sequence[float]] | None) -> np.ndarray:
    mat = np.eye(3, dtype=np.float32)
    if not basis:
        return mat
    arr = np.asarray(basis, dtype=np.float32)
    if arr.shape == (3, 3):
        return arr
    return mat


def _parent_cell_count(basis: np.ndarray) -> int:
    det = abs(float(np.linalg.det(np.asarray(basis, dtype=float))))
    n = int(round(det))
    return max(n, 1)


def compute_gd_bundle(
    *,
    cif: Path,
    k_label: str,
    irrep: str,
    opd: str,
    k_params: list[str],
    nmod: int,
    cris_root: Path,
    language: str = "en",
) -> GdBundle:
    _ensure_isocore(cris_root)
    from isocore.api import IsoDistort
    from isocore.io.distortion_formats import cart_normalized_mode_matrix

    cif = Path(cif)
    if not cif.is_file():
        raise FileNotFoundError(cif)

    iso = IsoDistort(language=language)
    iso.set_distortion_types(["strain", "displacive"])
    iso.set_distortion_scope({
        "displacive": ["*"],
        "occupational": [],
        "strain": [],
        "magnetic": [],
        "rotational": [],
    })
    iso.load_structure(cif)
    subs = iso.list_subgroups_at(
        k_label, irrep, k_parameters=list(k_params), generate_if_missing=False,
    )
    target = next(
        (
            s for s in subs
            if s.irrep_label == irrep and str(s.opd_symbol).upper() == opd.upper()
        ),
        None,
    )
    if target is None:
        available = sorted({f"{s.irrep_label}:{s.opd_symbol}" for s in subs})
        raise RuntimeError(
            f"{irrep} {opd} not in Method-2 list at {k_label} "
            f"{k_params}; have {available[:20]}"
        )
    iso.search_method_2(
        target.index,
        candidates=subs,
        number_of_independent_modulations=int(nmod),
    )
    sc = iso._supercell_for_subgroup(target)
    disp_map = dict(getattr(iso, "mode_displacements_sc", None) or {})
    labels = dict(getattr(iso, "_mode_label_overrides", None) or {})
    ordered_keys: list[str] = []
    for mode in iso.distortion_modes or []:
        key = iso._mode_session_key(mode)
        if key in disp_map and key not in ordered_keys:
            ordered_keys.append(key)
    for key in disp_map:
        if key not in ordered_keys:
            ordered_keys.append(key)
    if not ordered_keys:
        raise RuntimeError("Method 2 returned no supercell displacive modes")

    n_cells = _parent_cell_count(target.basis_vectors or np.eye(3))
    names: list[str] = []
    vectors: list[np.ndarray] = []
    norms: list[float] = []
    bounds: list[float] = []
    lattice = np.asarray(sc.lattice.matrix, dtype=float)
    for key in ordered_keys:
        raw = np.asarray(disp_map[key], dtype=float)
        if raw.shape != (len(sc), 3):
            raise RuntimeError(
                f"mode {key} has shape {raw.shape}, supercell has {len(sc)} atoms"
            )
        scaled, maxamp = cart_normalized_mode_matrix(
            raw, lattice, centering_mult=n_cells
        )
        names.append(labels.get(key) or key)
        vectors.append(np.asarray(scaled, dtype=np.float32))
        # cart-normalized vectors already have primitive Cartesian RMS = 1 Å
        # per unit amplitude, so the notebook's extra scale is identity.
        norms.append(1.0)
        bounds.append(float(maxamp))

    mode_frac = np.stack(vectors, axis=0)
    base_frac = np.asarray(sc.frac_coords, dtype=np.float32)
    species = [str(site.species_string) for site in sc]
    parent_sg = int((iso.symmetry_info or {}).get("space_group_number") or 0)
    parent_sym = str(
        (iso.symmetry_info or {}).get("space_group_symbol") or parent_sg
    )
    hkl_t = _hkl_transform_from_basis(target.basis_vectors)
    meta = {
        "cif": str(cif),
        "k_label": k_label,
        "k_params": list(k_params),
        "irrep": irrep,
        "opd": opd,
        "nmod": int(nmod),
        "parent_sg": parent_sg,
        "parent_symbol": parent_sym,
        "child_sg": int(target.space_group_number or 0),
        "child_symbol": str(target.space_group_symbol or ""),
        "basis": [list(map(float, row)) for row in (target.basis_vectors or [])],
        "origin": list(map(float, target.origin or [0, 0, 0])),
        "n_modes": len(names),
        "n_atoms": len(species),
        "parent_cells_in_supercell": n_cells,
        "maxamp_convention": "sqrt(N_parent_cells) after primitive Cartesian RMS = 1",
        "norm_factors": "1 (mode vectors already cart-normalized)",
    }
    return GdBundle(
        names=names,
        norm_factors=np.asarray(norms, dtype=np.float32),
        max_bounds=np.asarray(bounds, dtype=np.float32),
        species=species,
        base_frac=base_frac,
        mode_frac=mode_frac,
        lattice=np.asarray(lattice, dtype=np.float32),
        hkl_transform=hkl_t,
        parent_symbol=parent_sym,
        irrep=irrep,
        opd=opd,
        metadata=meta,
    )


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cif", type=Path, default=DEFAULT_CIF)
    p.add_argument("--k", dest="k_label", default="LD")
    p.add_argument("--k-params", nargs="+", default=["1/6"])
    p.add_argument("--irrep", default="LD1")
    p.add_argument("--opd", default="C1")
    p.add_argument("--nmod", type=int, default=0)
    p.add_argument("--cris", type=Path, default=DEFAULT_CRIS)
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output directory (default: generated/{irrep}_{opd})",
    )
    p.add_argument(
        "--prefix",
        default=None,
        help="File prefix (default: {irrep}_{opd})",
    )
    p.add_argument(
        "--install-alris",
        action="store_true",
        default=True,
        help="Also write {prefix}_alris_functions.py next to this script (notebook import).",
    )
    p.add_argument(
        "--no-install-alris",
        action="store_false",
        dest="install_alris",
    )
    return p


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    prefix = args.prefix or f"{args.irrep}_{args.opd}"
    out_dir = args.out or (GD_ROOT / "generated" / prefix)
    install = (GD_ROOT / f"{prefix}_alris_functions.py") if args.install_alris else None
    bundle = compute_gd_bundle(
        cif=args.cif,
        k_label=args.k_label,
        irrep=args.irrep,
        opd=args.opd,
        k_params=list(args.k_params),
        nmod=int(args.nmod),
        cris_root=args.cris,
    )
    problems = check_bundle(bundle)
    if problems:
        raise SystemExit("bundle failed checks: " + "; ".join(problems))
    written = write_gd_bundle(out_dir, prefix, bundle, install_alris=install)
    print(f"wrote {bundle.metadata['n_modes']} modes, "
          f"{bundle.metadata['n_atoms']} atoms -> {out_dir}")
    for key, path in written.items():
        print(f"  {key}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
