"""distortion 包 - 畸变业务层（项目核心）"""
from .affine_embeddings import (
    AffineEmbedding,
    AffineOperation,
    AffineQuotient,
    ParentAffineGroup,
    affine_equivalence,
    build_affine_quotient,
    embedding_from_identity,
    enumerate_lifted_point_subgroups,
    enumerate_target_affine_embeddings,
    locate_embedding_subgroup,
    parent_affine_group,
)
from .distortion_engine import DistortionEngine
from .distortion_mapper import DistortionMapper
from .domain_generator import DomainGenerator
from .inverse_landau import (
    ExactCharacterRepresentation,
    FiniteGroup,
    FixedSpaceFeasibility,
    FixedSpaceFeasibilityAnalyzer,
    FixedSpaceFeasibilitySummary,
    RationalRepresentation,
    analyze_fixed_space,
    character_representation,
    direct_sum_character_representations,
    direct_sum_representations,
    fixed_space_basis,
    fixed_space_projector,
    homogeneous_strain_representation,
    pointwise_stabilizer,
    polar_vector_representation,
    remove_uniform_site_vectors,
    site_displacement_representation,
    site_scalar_representation,
    site_vector_character_representation,
    site_vector_representation,
    symmetric_square_representation,
)
from .inverse_landau_adapter import (
    DiagnosticCharacterRepresentationBundle,
    DiagnosticRepresentationBundle,
    EmbeddingFeasibilityDiagnostic,
    build_selected_character_representation,
    build_selected_representation,
    diagnose_embedding_feasibility,
    parent_frame_fingerprint,
    quotient_finite_group,
    stable_embedding_id,
)
from .occupational_modes import OccupationalMode, OccupationalModeGenerator
from .phase_path import (
    DEFAULT_DISTORTION_TYPES,
    DISTORTION_TYPES,
    TYPE_ALIASES,
    PhasePath,
    normalize_distortion_types,
)
from .search_methods import (
    IsoSearchEngine,
    Method1Query,
    Method1ResultItem,
    Method2Query,
    Method2Result,
    Method3Query,
    Method3ResultItem,
    Method4Query,
    Method4Result,
)
from .superspace import ParametricModeResult, compute_parametric_modes

__all__ = [
    "DEFAULT_DISTORTION_TYPES",
    "DISTORTION_TYPES",
    "TYPE_ALIASES",
    "AffineEmbedding",
    "AffineOperation",
    "AffineQuotient",
    "DiagnosticCharacterRepresentationBundle",
    "DiagnosticRepresentationBundle",
    "DistortionEngine",
    "DistortionMapper",
    "DomainGenerator",
    "EmbeddingFeasibilityDiagnostic",
    "ExactCharacterRepresentation",
    "FiniteGroup",
    "FixedSpaceFeasibility",
    "FixedSpaceFeasibilityAnalyzer",
    "FixedSpaceFeasibilitySummary",
    "IsoSearchEngine",
    "Method1Query",
    "Method1ResultItem",
    "Method2Query",
    "Method2Result",
    "Method3Query",
    "Method3ResultItem",
    "Method4Query",
    "Method4Result",
    "OccupationalMode",
    "OccupationalModeGenerator",
    "ParametricModeResult",
    "ParentAffineGroup",
    "PhasePath",
    "RationalRepresentation",
    "affine_equivalence",
    "analyze_fixed_space",
    "build_affine_quotient",
    "build_selected_character_representation",
    "build_selected_representation",
    "character_representation",
    "compute_parametric_modes",
    "diagnose_embedding_feasibility",
    "direct_sum_character_representations",
    "direct_sum_representations",
    "embedding_from_identity",
    "enumerate_lifted_point_subgroups",
    "enumerate_target_affine_embeddings",
    "fixed_space_basis",
    "fixed_space_projector",
    "homogeneous_strain_representation",
    "locate_embedding_subgroup",
    "normalize_distortion_types",
    "parent_affine_group",
    "parent_frame_fingerprint",
    "pointwise_stabilizer",
    "polar_vector_representation",
    "quotient_finite_group",
    "remove_uniform_site_vectors",
    "site_displacement_representation",
    "site_scalar_representation",
    "site_vector_character_representation",
    "site_vector_representation",
    "stable_embedding_id",
    "symmetric_square_representation",
]
